const Discord = require('discord.js');

const constants = require('../constants.js');
const client = constants.client;
const audioStreamPerGuild = constants.audioStreamPerGuild;
const voiceChannelPerGuild = constants.voiceChannelPerGuild;

client.on('voiceStateUpdate', async(oldState, newState) => {
	if (newState.member.user.bot) return;

	if (oldState.channelID && newState.channelID) return;

	if (oldState && oldState.channelID && oldState.channelID !== newState.channelID) {
		let member = newState.member;

		// If the user left a voice recording channel(generated by bot), this event should not be called and so return
		if (voiceChannelPerGuild[oldState.guild.id] && oldState.channelID === voiceChannelPerGuild[oldState.guild.id]['voice_channel_id']) return;
		
		if (audioStreamPerGuild[member.guild.id] && audioStreamPerGuild[member.guild.id].recorder) {
			
			let recorder = audioStreamPerGuild[member.guild.id].recorder;
			let userId = audioStreamPerGuild[member.guild.id].author_id;

			if (recorder.getIsRecording() && userId === member.user.id) {
				member.user.send("It looks like you left mid-recording. I couldn't record your voice anymore because you left the voice channel.\n----------------");
				member.guild.me.voice.channel.leave();
			}
		}
	}
});
